### ISSUE TITLE
calculate and show deviation from our "median of medians"

### ISSUE THREAD

**Issue by lindsaycarr** [USGS-VIZLAB/gage-conditions-gif#66]
How do we want to represent and calculate the deviation from our "median of medians"?

**Comment by lindsaycarr** [comment]
@aappling-usgs and I had a long conversation about this. Ultimately, we decided that we did not want to continue with "median of medians" and will stick with showing the daily values based on their relation to the hydrologic history of a given day.

Here's the long explanation:

Currently, each site on each day is colored based on how it compares to the flow at that site for every other day in that site's record. We are using the stat service to get the percentiles for each day for each site. With this method, our red colors show when the site's daily value drops below the median value typically seen on that same day of the year for that same site. So, we are showing each day in relation to previous years. In the end, you are seeing a picture of what makes water year 2018 different from previous years. The "median" value at each site changes over the year. This method makes it possible to build this GIF again for next year and say "here is how WY19 differs from WY18". 

Alternatively, we were thinking about calculating the median value at each site for the whole year - (take each site's median value for each day of 2018 and calculate the median of those). We were planning to use this as a proxy for "baseflow", then we would color the sites based on their deviation from this "baseflow" value. Higher than baseflow would become bluer, lower than baseflow would become more red. We realized that this would be a great way to show seasonal changes within a given year - winter is drier, spring is wetter, etc. BUT we wondered how different this would look from year to year. WY19 should show similar seasonal patterns to WY18 - dry in winter, wet in spring, and so on.

Both could be useful but it depends on the goal. If the goal is to educate people about seasonal patterns within a water year - wet seasons, dry seasons - then using "median of medians" would be useful. However, if the goal is to show what makes a given water year unique to previous ones - where were the abnormalities - then we think using the daily stats is the way to go. By discussing the differences between these methods, we did find that there might be an issue with how the colors are being assigned currently. That will be worked implemented. See #74. 

We are chose the goal of showing the uniqueness of WY18, but can change direction after discussion with GWSIP.

**Comment by jread-usgs** [comment]
I have a few thoughts to add here. But initially, although the 'median of the medians' sounds more complex than what we are doing currently, it is meant to be simpler and instead be a period of record set of percentiles as opposed to the DOY-specific set of percentiles. Since we aren't pulling in the entire period of record and calculating percentiles, taking averages (or medians) of all DOY statistics gets us most of the way there. 

Removing seasonality is an additional step of processing (kind of like de-trending would be) and therefore raises the bar for the public being able to interpret what is going on in the animation. If we go down that route, we'd want a really good reason. Showing events as DOY-specific anomalies is a good reason, and I think it is defensible. The question I have is whether we can/should make the leap from having no public animation of daily stream conditions to one that has an additional layer of statistical treatment to it (DOY varying percentiles for each site vs static percentiles for each site). Would we accidentally spread the false knowledge that there isn't seasonality in streamflow? 

It is clear that are good reasons to choose one over the other in this situation - there isn't a simple answer, but I think it comes down to the goals and the expectations we have for audience interpretation.

**Comment by lindsaycarr** [comment]
Decision: seasonality is not the immediate GWSIP need. Solution: move forward with WY18 only, keeping seasonality in mind for interactive version.
